### PR TITLE
Bring back Python 2.6 compatibility

### PR DESCRIPTION
**Pull request by selurvedu**
dict.viewkeys() is only available in Python 2.7.

From https://docs.python.org/2/library/stdtypes.html#dict.viewkeys:

> viewkeys()
>    Return a new view of the dictionary’s keys. See below for documentation of view objects.
>    **New in version 2.7.**

### CODE REVIEW

**Comment by nxsofsys** [comment]
So what value of _viewkeys will be on python 2.6?

**Comment by selurvedu** [comment]
> So what value of _viewkeys will be on python 2.6?

dict.keys

**Comment by selurvedu** [comment]
New commit: I completely forgot that `.major` and `.minor` were added in 2.7 too.

From https://docs.python.org/2.7/library/sys.html#sys.version_info:

> sys.version_info
> **Changed in version 2.7: Added named component attributes**

**Comment by nxsofsys** [comment]
hm, i see following error:

```
Python 2.6.6 (r266:84297, Aug 24 2010, 18:46:32) [MSC v.1500 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>>
>>> if sys.version_info[0] == 2:
...     _range = xrange
...     if sys.version_info[1] == 7:
...         _viewkeys = dict.viewkeys
... else:
...     _range = range
...     _viewkeys = dict.keys
...
>>> print (_viewkeys)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name '_viewkeys' is not defined
```

Moreover, _viewkeys should return set-like type, which not  returned type of dict.keys in python 2

**Comment by nxsofsys** [comment]
I've fixed this in other way, thanks for issue!

**Comment by selurvedu** [comment]
Right, I should have tested it on real Python 2.6 interpreter, not just inside my head. :)

**Comment by selurvedu** [comment]
@nxsofsys, yay, it finally works on both 2.6 and 3.2! :smile:
https://travis-ci.org/selurvedu/python-json-patch/builds/86235936

**Comment by nxsofsys** [comment]
cool!

**Pull request closed without merging**
